# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "iD5mmzAb9OD4t4YRq048wUPAY3/r+4+1wgF89lBbL6oXwvUTgQLapCAj/qRUJj5E+Y5nE5lZDViPQRn6ROjGrUrKhNh4aI7xVRhyNBR9XorJdVf51yf1wQOFAML07vHs76Qb91icNPVC8SqNe1JMMuue96MQS//yyXGUN6TXOxm+XOdhBxfRyRW0tF6GFVEVhOouRCQcdPjChzAjmMP8tYzFh3INxSBUZNaQhKgTlbFBk5IUgviVfWefLVSTnxc1DPiE7i08mPLlQ4Sxx+LRIMj3eyaKHTJtgjl1Gcz2kJNVyh+WkqAd8YH0WWgGK5tzmU6RUmPFFiFh6pXjAD1FyZBNA2gb9yE6JjIOIOFtUrBcaIb1r7b+juY+/6tmbPI3IaoCeEGEJv7zp41A6Gnr2Cw+O5MLseriXpRutiQ32w60ZNkRVflQc4KCeBN8vVh2kHsWkmu6h6YabLTPDGBRr67EDHu0W5lSMf7W/gqppND+QkHMSkN4jSd+5QXO23IWsYepC99zY5Cp8Ruv8TvwuwWCUcehPvSVRVQmNYj9wlj3y3+1mPsxDrYVRTpFWz/AuiwDLF2DP0uTkNEzEt36XQtj2tX1GizbdF38bs6R5ewNFiHcNXPZ7cKaN6EYto3uZABJ+KFxkqoYObIMamf8OC6X1vTDVmNtqFtCTrD3G4M="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
