travis:
  secure:
    BINSTAR_TOKEN: iD5mmzAb9OD4t4YRq048wUPAY3/r+4+1wgF89lBbL6oXwvUTgQLapCAj/qRUJj5E+Y5nE5lZDViPQRn6ROjGrUrKhNh4aI7xVRhyNBR9XorJdVf51yf1wQOFAML07vHs76Qb91icNPVC8SqNe1JMMuue96MQS//yyXGUN6TXOxm+XOdhBxfRyRW0tF6GFVEVhOouRCQcdPjChzAjmMP8tYzFh3INxSBUZNaQhKgTlbFBk5IUgviVfWefLVSTnxc1DPiE7i08mPLlQ4Sxx+LRIMj3eyaKHTJtgjl1Gcz2kJNVyh+WkqAd8YH0WWgGK5tzmU6RUmPFFiFh6pXjAD1FyZBNA2gb9yE6JjIOIOFtUrBcaIb1r7b+juY+/6tmbPI3IaoCeEGEJv7zp41A6Gnr2Cw+O5MLseriXpRutiQ32w60ZNkRVflQc4KCeBN8vVh2kHsWkmu6h6YabLTPDGBRr67EDHu0W5lSMf7W/gqppND+QkHMSkN4jSd+5QXO23IWsYepC99zY5Cp8Ruv8TvwuwWCUcehPvSVRVQmNYj9wlj3y3+1mPsxDrYVRTpFWz/AuiwDLF2DP0uTkNEzEt36XQtj2tX1GizbdF38bs6R5ewNFiHcNXPZ7cKaN6EYto3uZABJ+KFxkqoYObIMamf8OC6X1vTDVmNtqFtCTrD3G4M=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
